name: This is my First CI/CD Workflow
on: 
  push:
    branches: ['main']
jobs:
  first-job:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Print Welcome 
        run: echo "welcome to first workflow"        
