name: This is my First CI/CD Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Welcome 
        run: echo "welcome to first workflow"        
