name: example-workflow
on: [push]
jobs:
  production-deploy:
    if: "contains(github.event.head_commit.message, 'Second Commit')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
      - run: npm install -g bats



        
       
