name: Scheduled Workflow
on:
  schedule:
    - cron: '* * * * *' # Runs every minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          # Commands to run tests
       


        
       
