name: Scheduled Workflow
on:
  schedule:
    - cron: '00 20 24 7 3' # Runs on 3 PM 45 minutes every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          # Commands to run tests
       


        
       
